import { useState } from "react";
import { calculateMonthlyCost } from "../../lib/calculator";
import { Field } from "../../components/UI";

type Mode = "attempts" | "calls";

const defaultState = {
  mode: "attempts" as Mode,
  inputTokens: 1000,
  outputTokens: 500,
  attempts: 1000,
  callsPerAttempt: 2,
  calls: 2000,
  inputPerMillion: 1,
  outputPerMillion: 4,
  otherMonthly: 0,
  successRate: 80,
  humanReviewMinutes: 2,
  humanHourlyRate: 60,
};

type CostState = typeof defaultState;

/**
 * A dedicated, self-contained editorial section for cost modeling —
 * separate from the comparison scorecard above, per the plan's "redesign
 * pattern comparison and cost calculator as separate editorial sections."
 * Every input carries an explicit unit/semantics hint, and a mode toggle
 * makes the calculator's actual calls-versus-attempts arithmetic
 * (`src/lib/calculator.ts`) directly observable rather than implicit.
 */
export function CostModel() {
  const [state, setState] = useState<CostState>(defaultState);

  const setField =
    (key: keyof CostState) => (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = Math.max(0, Number(e.target.value) || 0);
      setState((s) => ({ ...s, [key]: value }));
    };

  const input =
    state.mode === "attempts"
      ? {
          inputTokens: state.inputTokens,
          outputTokens: state.outputTokens,
          attempts: state.attempts,
          callsPerAttempt: state.callsPerAttempt,
          inputPerMillion: state.inputPerMillion,
          outputPerMillion: state.outputPerMillion,
          otherMonthly: state.otherMonthly,
          successRate: state.successRate,
          humanReviewMinutes: state.humanReviewMinutes,
          humanHourlyRate: state.humanHourlyRate,
        }
      : {
          inputTokens: state.inputTokens,
          outputTokens: state.outputTokens,
          calls: state.calls,
          inputPerMillion: state.inputPerMillion,
          outputPerMillion: state.outputPerMillion,
          otherMonthly: state.otherMonthly,
          successRate: state.successRate,
          humanReviewMinutes: state.humanReviewMinutes,
          humanHourlyRate: state.humanHourlyRate,
        };

  let result: ReturnType<typeof calculateMonthlyCost> | undefined;
  let calculationError = "";
  try {
    result = calculateMonthlyCost(input);
  } catch (error) {
    calculationError = (error as Error).message;
  }

  return (
    <section className="cost-model" aria-labelledby="cost-model-heading">
      <h2 id="cost-model-heading">Explicit-input cost model</h2>
      <p>
        Every field below states its own unit. The defaults are hypothetical
        inputs, not live provider prices — replace them with your own
        measured numbers before trusting the total.
      </p>
      <fieldset className="cost-mode">
        <legend>How do you count monthly usage?</legend>
        <label className="cost-mode-option">
          <input
            type="radio"
            name="cost-mode"
            checked={state.mode === "attempts"}
            onChange={() => setState((s) => ({ ...s, mode: "attempts" }))}
          />
          Attempts &times; calls per attempt
        </label>
        <label className="cost-mode-option">
          <input
            type="radio"
            name="cost-mode"
            checked={state.mode === "calls"}
            onChange={() => setState((s) => ({ ...s, mode: "calls" }))}
          />
          Raw model call count
        </label>
      </fieldset>
      <div className="calc-grid">
        <Field
          label="Input tokens per call"
          hint="Tokens sent to the model in a single call"
        >
          <input
            type="number"
            min="0"
            value={state.inputTokens}
            onChange={setField("inputTokens")}
          />
        </Field>
        <Field
          label="Output tokens per call"
          hint="Tokens generated by the model in a single call"
        >
          <input
            type="number"
            min="0"
            value={state.outputTokens}
            onChange={setField("outputTokens")}
          />
        </Field>
        {state.mode === "attempts" ? (
          <>
            <Field
              label="Attempts per month"
              hint="Business tasks attempted per month, not model calls"
            >
              <input
                type="number"
                min="0"
                value={state.attempts}
                onChange={setField("attempts")}
              />
            </Field>
            <Field
              label="Calls per attempt"
              hint="Model calls per attempt, including expected retries"
            >
              <input
                type="number"
                min="0"
                value={state.callsPerAttempt}
                onChange={setField("callsPerAttempt")}
              />
            </Field>
          </>
        ) : (
          <Field
            label="Model calls per month"
            hint="Raw call count for the month, already including any retries"
          >
            <input
              type="number"
              min="0"
              value={state.calls}
              onChange={setField("calls")}
            />
          </Field>
        )}
        <Field
          label="Input price per million tokens"
          hint="Your currency per 1,000,000 input tokens"
        >
          <input
            type="number"
            min="0"
            value={state.inputPerMillion}
            onChange={setField("inputPerMillion")}
          />
        </Field>
        <Field
          label="Output price per million tokens"
          hint="Your currency per 1,000,000 output tokens"
        >
          <input
            type="number"
            min="0"
            value={state.outputPerMillion}
            onChange={setField("outputPerMillion")}
          />
        </Field>
        <Field
          label="Other fixed monthly cost"
          hint="Hosting, tools or fees not covered by token usage"
        >
          <input
            type="number"
            min="0"
            value={state.otherMonthly}
            onChange={setField("otherMonthly")}
          />
        </Field>
        <Field
          label="Success rate"
          hint="Percent of attempts reaching a verified successful outcome (0-100)"
        >
          <input
            type="number"
            min="0"
            max="100"
            value={state.successRate}
            onChange={setField("successRate")}
          />
        </Field>
        <Field
          label="Human review minutes"
          hint="Minutes of human review per attempt, not per model call"
        >
          <input
            type="number"
            min="0"
            value={state.humanReviewMinutes}
            onChange={setField("humanReviewMinutes")}
          />
        </Field>
        <Field
          label="Human hourly rate"
          hint="Fully loaded reviewer cost per hour, in your currency"
        >
          <input
            type="number"
            min="0"
            value={state.humanHourlyRate}
            onChange={setField("humanHourlyRate")}
          />
        </Field>
      </div>
      {calculationError && (
        <p className="form-error" role="alert">
          {calculationError}
        </p>
      )}
      {result && (
        <output aria-label="Monthly cost result" className="cost-result">
          <p>{result.totalCalls.toLocaleString()} model calls per month.</p>
          <p>
            Model usage: ${result.usage.toFixed(2)} &middot; Human review: $
            {result.human.toFixed(2)} &middot; Monthly total:{" "}
            <strong>${result.monthly.toFixed(2)}</strong>
          </p>
          <p>
            Cost per successful outcome:{" "}
            <strong>
              {result.costPerSuccess === null
                ? "n/a"
                : `$${result.costPerSuccess.toFixed(2)}`}
            </strong>{" "}
            ({result.successfulOutcomes.toFixed(1)} estimated verified
            outcomes)
          </p>
        </output>
      )}
    </section>
  );
}
