import fs from 'node:fs';
// One-time mechanical composition of separately authored examples into the JSON corpus.
const root=new URL('../src/content/',import.meta.url);
const guides=JSON.parse(fs.readFileSync(new URL('guides.json',root)));
const examples={
  architecture:[['A concrete state contract','Hypothetical notification state table: proposed -> awaiting approval only after target validation; awaiting approval -> ready only with an unexpired approval matching the action hash; ready -> dispatched after reserving an operation ID; dispatched -> verified only after provider status confirms the intended recipient; dispatched -> outcome unknown on timeout. Outcome unknown may move to verified, confirmed-not-sent or manual reconciliation. Cancellation stops new dispatch but does not erase an in-flight send. Record transitions with actor, timestamp and expected state version.']],
  'workflow-patterns':[['Choose a pattern for each dependency','Hypothetical report pipeline: parse -> extract -> validate is sequential because each step consumes the previous output. Inspect three independent source documents in fan-out workers, then fan-in with an explicit missing-result policy. Route known document types by validated metadata. Use an orchestrator only if the needed subtasks are not known until evidence arrives. An evaluator may request one correction with a concrete failed criterion; after the effort budget, preserve the unresolved issue rather than looping. A person approves the final recipient list before delivery.']],
  'tool-design':[['A tool contract and its approval record','Hypothetical send_report input: projectId:string, reportId:string, recipientId:string, expectedReportVersion:integer, operationId:string. Domain checks: caller owns project; report belongs to project; recipient is permitted; version matches; operation ID has not been used for different parameters. Approval record: action=send_report, parametersHash=<hash of canonical validated input>, approverId, approvedAt, expiresAt, policyVersion. Dispatch compares the exact hash and current authority. Result is one of rejected, accepted(operationId), verified(providerMessageId), or outcome_unknown(operationId). Never return verified merely because dispatch returned HTTP 202.']],
  'durable-execution':[['Ambiguous timeout: failed and corrected recovery','Hypothetical trace: 10:00:00 persist intent op-42; 10:00:01 provider accepts op-42; 10:00:02 connection drops; 10:00:03 worker dies. Failed recovery creates op-43 and sends again. Corrected recovery reloads op-42 as outcome unknown, queries the provider, records its message ID and verifies the recipient. If status lookup is unavailable, stop automatic retries and assign reconciliation. If confirmed not sent, retry only under the documented same-key semantics. Test both crashes: after remote acceptance and after local confirmation.']],
  security:[['Confused deputy: an allowed reader and an allowed sender','Hypothetical attack: a retrieved ticket tells the assistant to read a confidential file and email it to a new address. The connector is authenticated, but that does not make the document authoritative. Enforce caller-and-object authorization on the read, minimize data exposed to the worker, and apply destination/data policy on the send. The approval screen must display the real recipient and content scope, not a model-written assurance. Record the rejected operation and source ID. If data already left, disable further sends and follow incident reconciliation. Destination allowlists alone do not prevent leaks to an allowed recipient; review information flow and residual risk.']],
  evaluations:[['A usable evaluation report template','Hypothetical report, not a benchmark: dataset v3 has 200 independently sampled cases; 180 verified outcomes pass, so observed success is 90%. Report a binomial interval with its method (for example Wilson), rather than reporting 90% as exact reliability. If zero severe failures are observed, the rough rule-of-three upper bound is 3/200=1.5% at approximately 95% confidence under independent representative trials; clustered or biased samples weaken that interpretation. Report language/document segments with their own denominators. Compare old and new versions on the same cases, list improved/regressed pairs, and review disagreements. Record human label disagreements and their adjudication. Release depends on consequence-specific thresholds and unresolved severe cases, not this illustrative percentage.']],
  retrieval:[['A small retrieval acceptance set','Hypothetical fixtures: Q1 asks a current order status and must use the order API; Q2 asks a policy exception and needs page 4 of policy v2; Q3 asks for a deleted document and must not retrieve its old chunks; Q4 uses a similar title in another tenant and must return no unauthorized passage; Q5 asks a table value whose unit crosses a page break. For each, record extracted text, expected evidence IDs, retrieved evidence IDs, authorization result and answer citations. Fix extraction before reranking if Q5 lost its unit.']],
  'framework-selection':[['Hard gates before preferences','Hypothetical selection sheet: durable resume after worker loss=required; approvals bound to exact parameters=required; chosen deployment/language=required; tenant isolation=required; exportable state=required. For each option record pass, fail or unverified with a dated artifact. One failed requirement excludes the option for this scope; one unverified requirement prevents qualification. Only then compare preferences such as team familiarity, implementation effort and operating cost with explicit weights. Repeat the same failure scenario in every candidate. Model/provider sheet: task quality, required tool/schema behavior, data handling, latency, quotas and fallback equivalence each need separate evidence.']],
  'release-operations':[['A release and rollback record','Hypothetical release r17: code commit, prompt hash, model identifier, tool schema v4, index v8, memory policy v2 and eval dataset v3. Eligible traffic: internal draft-only requests, maximum 50/day. Owner: named on-call person. Stop conditions: any unauthorized write, unresolved severe privacy event, or sustained review queue above staffed capacity. Rollback artifact: r16 image and compatible state policy. Drill: stop intake, drain/reconcile in-flight operations, switch version, verify a read-only case and inspect pending jobs. Record actual observations and who accepted remaining gaps.']],
  'cost-capacity':[['A cost scenario with review labor','Hypothetical month: 1,000 attempts, 800 verified successes, 80 currency units in model/tool usage, 40 in infrastructure and 10 hours of review at 30/hour. Total cost is 420; cost per verified success is 420/800=0.525 currency units. Include failed attempts in the 1,000 rather than multiplying their cost twice. If no successes occur, the metric is undefined. Compare the same business outcomes and review quality with the baseline. Prices here are invented example inputs, not provider quotes.']],
  memory:[['A correction record','Hypothetical preference: project=A, user=U, key=report_format, value=PDF, provenance=explicit user request, observedAt=t1. At t2 the user requests HTML. Store the correction as superseding the old value, invalidate derived summaries/caches and verify the next retrieval returns HTML under the same namespace. A similar preference in project B is untouched. Retention/deletion policy must describe when both the current and superseded records disappear. This preference cannot grant permission to send a report.']]
};
for(const g of guides)for(const [title,body]of examples[g.id]||[])if(!g.examples.some(e=>e.title===title))g.examples.push({title,body});
fs.writeFileSync(new URL('guides.json',root),JSON.stringify(guides,null,2)+'\n');
console.log('Composed authored worked artifacts into guide examples.');
const sources=JSON.parse(fs.readFileSync(new URL('sources.json',root)));
const stats={id:'nist-proportions',title:'NIST: confidence intervals for proportions',url:'https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm',reviewedAt:'2026-09-15',status:'reviewed',notes:'Supports the binomial/Wilson interval discussion. The rule-of-three example is an approximate binomial calculation with independence assumptions, not a production risk guarantee.'};
if(!sources.some(s=>s.id===stats.id))sources.push(stats);
for(const s of sources)if(s.id.startsWith('framework-')&&!s.notes.includes('Reverify'))s.notes+=' Reverify before selection, on a release/license change, or when this snapshot is older than 90 days. This is an editorial review policy, not a vendor guarantee.';
const ev=guides.find(g=>g.id==='evaluations');if(!ev.sourceIds.includes(stats.id))ev.sourceIds.push(stats.id);
fs.writeFileSync(new URL('guides.json',root),JSON.stringify(guides,null,2)+'\n');
fs.writeFileSync(new URL('sources.json',root),JSON.stringify(sources,null,2)+'\n');
const flows=JSON.parse(fs.readFileSync(new URL('troubleshooting.json',root)));
const more={
 'context-loss':[
 ['Storage loss','The authoritative record is missing before retrieval begins','Recover from a retained artifact or ask for the missing information','Separate durable task state from transient chat and test restoration'],
 ['Stale source','Retrieved content is an older source version despite correct selection','Consult the authoritative current version before acting','Propagate document updates and record lineage/version in context']
 ],
 'tool-failure':[
 ['Argument rejected before dispatch','Validation log shows the request never left the application','Correct the invalid field; do not retry unchanged input','Make schema and semantic errors actionable and test malformed arguments'],
 ['Authorization denied','Policy check denies the caller, target or current action','Stop and request a properly scoped decision; never bypass the check','Enforce per-object authorization and clarify permitted actions'],
 ['Accepted but not completed','Provider returns an operation ID or pending status without the postcondition','Poll within a deadline or expose pending status','Distinguish accepted, pending, verified and failed outcomes in the tool contract'],
 ['Postcondition mismatch','Provider reports success but the wrong target/version changed','Stop further writes and reconcile affected records','Verify business invariants and actual external state before completion'],
 ['Missing observability','There is no trustworthy operation ID or dispatch record','Preserve uncertainty and assign manual investigation','Add correlated intent, dispatch, provider and verification records']
 ],
 'cost-latency':[
 ['Demand or task mix changed','More tasks or longer inputs arrived without a comparable traffic baseline','Apply the defined admission limits and review the workload','Forecast by task class and distinguish volume from per-task cost'],
 ['Provider throttling','Rate-limit responses or quota usage correlate with delays','Reduce concurrency and honor bounded backoff','Align admission control and validated fallback with provider quotas'],
 ['Human-review bottleneck','Automated stages complete while approval queue age increases','Reduce action scope and prioritize critical reviews','Include staffed review capacity in throughput planning']
 ]
};
for(const f of flows)for(const [title,evidence,mitigation,durableFix]of more[f.id]||[])if(!f.causes.some(c=>c.title===title))f.causes.push({title,evidence,mitigation,durableFix});
fs.writeFileSync(new URL('troubleshooting.json',root),JSON.stringify(flows,null,2)+'\n');
const comparisons=JSON.parse(fs.readFileSync(new URL('comparisons.json',root)));
const strengths={
 'langgraph-langchain':['Explicit state/graph orchestration','Choice of lower-level runtime or higher-level integrations'],
 'microsoft-agent-framework':['.NET and Python agent/workflow abstractions','Documented migration paths from Microsoft predecessors'],
 crewai:['Role-based teams','Explicit event-driven flows alongside autonomous crews'],
 'google-agent-development-kit-adk':['Multi-language documentation','Multiple local and managed deployment paths'],
 pydanticai:['Typed dependencies and output contracts','Integration with Python validation tooling'],
 autogen:['Actor/runtime and AgentChat abstractions','Existing research and application ecosystem'],
 'semantic-kernel':['Kernel/plugin integration model','Useful fit for existing .NET and other SDK investments'],
 llamaindex:['Data-centric retrieval components','Current event-driven workflow abstractions'],
 haystack:['Composable retrieval/pipeline components','Self-hostable Python application integration'],
 agno:['Agents, teams and workflows','Separately described runtime and control-plane layers'],
 'strands-agents':['Python and TypeScript harness options','Provider and deployment integrations'],
 temporal:['Durable application workflow state','Self-hosted and managed service choices'],
 'azure-durable-functions':['Stateful orchestration in Functions','Integration with Azure operational environments'],
 'dapr-workflow':['Workflow building block beside other Dapr capabilities','Sidecar-based application integration'],
 n8n:['Visual workflow authoring','Large connector catalogue'],
 hindsight:['Dedicated long-term memory layer','Can complement rather than replace a task runtime'],
 flue:['TypeScript-first agent definitions','Hooks for tools and workflow integrations'],
 paperclip:['Organizational task and budget visibility','Adapters to external agent runtimes']
};
for(const c of comparisons)if(strengths[c.id])c.strengths=strengths[c.id];
const baselines=[
 {id:'thin-custom',name:'Thin custom loop + provider SDK',layer:'Custom baseline',summary:'A small application-owned loop around a model API and a restricted set of tools.',languages:'Choose a language supported by the selected SDK or HTTP API.',deployment:'Your existing application or worker environment.',strengths:['Direct visibility into control flow','No agent framework required for a small loop'],limitations:['You implement state, policy, budgets, retries and verification.','Provider capabilities and commercial terms need current verification.'],sourceIds:['agents','harnesses'],verifiedAt:'2026-09-15',evidenceStatus:'reviewed',license:'Your code and selected dependency licenses; provider terms separate.',maturity:'Architecture baseline, not a product release or vendor support claim.'},
 {id:'conventional-automation',name:'Conventional rules and integration',layer:'Non-AI baseline',summary:'Deterministic rules, scheduled jobs, APIs and queues without model decisions.',languages:'Use the team’s existing supported stack.',deployment:'Existing service, scheduler or queue worker.',strengths:['Explicit reproducible decision rules','Avoids model inference cost and variability'],limitations:['Ambiguous unstructured interpretation may require humans or a separate model step.','External effects still require authorization and recovery.'],sourceIds:['agents','retries'],verifiedAt:'2026-09-15',evidenceStatus:'reviewed',license:'Depends on selected components.',maturity:'Established engineering pattern; fitness depends on process stability and exceptions.'}
];
for(const b of baselines)if(!comparisons.some(c=>c.id===b.id))comparisons.push(b);
fs.writeFileSync(new URL('comparisons.json',root),JSON.stringify(comparisons,null,2)+'\n');
